sudo: required
language: bash
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - docker-compose build

before_script:
  - docker-compose up -d --force-recreate
  
script:
  - docker exec -it reinas_app_1 pytest -q test/tests.py --numero 7
  

